### ISSUE TITLE
Logger should write to stdout when script is run interactively

### ISSUE THREAD

**Issue by thenewwazoo** [outlook/openvpn-azure-ad-auth#4]
At present, log messages are "lost" when the script is run interactively, since the logger doesn't write to stdout. Update the script to add

```
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
```

in the interactive code path.

**Comment by stilljake** [comment]
@thenewwazoo I created a PR for this.

**Comment by mideeks** [comment]
https://github.com/outlook/openvpn-azure-ad-auth/issues/11
